apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: b4hochsd2-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0cc3fddae7.xb96.p3.openshiftapps.com/rhtap/rhtap-qe:2158c887cd82b9649c37ff2b5d4e52eab7f19540@sha256:efe1749245cfd2fc152b84d0eeeb3f76dbc02eae187869623d60d4171362e507
          name: container-image
